name: CI/CD Workflow for main branch
on: 
  [push]:
    branches:
      - main
jobs:
  test:
    # use the reusable workflow to check out the code, install dependencies
    # and run the Cypress tests
    # https://github.com/bahmutov/cypress-workflows
    uses: bahmutov/cypress-workflows/.github/workflows/standard.yml@v1
    # Incorrect use of path
    #uses: tranvantoan-qn/cypress-workflows/tree/main/.github/workflows/standard.yml@v1 
    #uses: tranvantoan-qn/cypress-workflows/.github/workflows/standard.yml@v1
    with:
      start: 'npm start'
      wait-on: 'http://localhost:3000/'
